// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: createFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, userId)
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, created_at, updated_at, name, url, userid
`

type createFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	Userid    uuid.NullUUID
}

func (q *Queries) createFeed(ctx context.Context, arg createFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.Userid,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.Userid,
	)
	return i, err
}
